# Lab 11 - Data Analysis
## vg-stats dataset 
### 12/16/2019

In [2]:
import pandas as pd
import numpy as np

In [4]:
video_games_df = pd.read_csv('vgsales.csv')

In [5]:
video_games_df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

## Which company is the most common video game publisher?

common_publishers = video_games_df['Publisher'].mode()[0]

In [12]:
common_publishers

'Electronic Arts'

In [14]:
video_games_df[video_games_df['Publisher'] == common_publishers]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
77,78,FIFA 16,PS4,2015.0,Sports,Electronic Arts,1.11,6.06,0.06,1.26,8.49
82,83,FIFA Soccer 13,PS3,2012.0,Action,Electronic Arts,1.06,5.05,0.13,2.01,8.24
83,84,The Sims 3,PC,2009.0,Simulation,Electronic Arts,0.98,6.42,0.00,0.71,8.11
92,93,Star Wars Battlefront (2015),PS4,2015.0,Shooter,Electronic Arts,2.93,3.29,0.22,1.23,7.67
99,100,Battlefield 3,X360,2011.0,Shooter,Electronic Arts,4.46,2.13,0.06,0.69,7.34
...,...,...,...,...,...,...,...,...,...,...,...
16339,16342,Command & Conquer Renegade,PC,2002.0,Shooter,Electronic Arts,0.00,0.01,0.00,0.00,0.01
16384,16387,Poker for Dummies,PC,2008.0,Misc,Electronic Arts,0.00,0.01,0.00,0.00,0.01
16413,16416,The Godfather (JP sales),X360,2006.0,Action,Electronic Arts,0.00,0.00,0.01,0.00,0.01
16539,16542,Spore Galactic Adventures,PC,2009.0,Strategy,Electronic Arts,0.00,0.01,0.00,0.00,0.01
16554,16557,Psychic Detective,PS,1995.0,Adventure,Electronic Arts,0.01,0.00,0.00,0.00,0.01

## Whatâ€™s the most common platform?

In [17]:
common_platforms = video_games_df['Platform'].mode()[0]

In [18]:
common_platforms

'DS'

## What about the most common genre?

In [19]:
common_genre = video_games_df['Genre'].mode()[0]

In [20]:
common_genre

'Action'

## What are the top 20 highest grossing games?

In [6]:
sorted_by_gross = video_games_df.sort_values('Global_Sales', ascending=False)

In [7]:
sorted_by_gross.head(20)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
10,11,Nintendogs,DS,2005.0,Simulation,Nintendo,9.07,11.00,1.93,2.75,24.76
11,12,Mario Kart DS,DS,2005.0,Racing,Nintendo,9.81,7.57,4.13,1.92,23.42
12,13,Pokemon Gold/Pokemon Silver,GB,1999.0,Role-Playing,Nintendo,9.00,6.18,7.20,0.71,23.10
13,14,Wii Fit,Wii,2007.0,Sports,Nintendo,8.94,8.03,3.60,2.15,22.72
14,15,Wii Fit Plus,Wii,2009.0,Sports,Nintendo,9.09,8.59,2.53,1.79,22.00
15,16,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
16,17,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
17,18,Grand Theft Auto: San Andreas,PS2,2004.0,Action,Take-Two Interactive,9.43,0.40,0.41,10.57,20.81
18,19,Super Mario World,SNES,1990.0,Platform,Nintendo,12.78,3.75,3.54,0.55,20.61
19,20,Brain Age: Train Your Brain in Minutes a Day,DS,2005.0,Misc,Nintendo,4.75,9.26,4.16,2.05,20.22

## For North American video game sales, whatâ€™s the median?

In [13]:
# na_sales = video_games_df['NA_Sales']
# # sorted_by_gross.median()
# na_sales.sort_values('Global_Sales', ascending=False)
# na_sales.median()

na_sales =  sorted_by_na_sales['NA_Sales']
sorted_by_na_sales = video_games_df.sort_values('NA_Sales', ascending=False)

In [90]:
na_sales_median = na_sales.median()

In [91]:
na_sales_median

0.08

## Provide a secondary output showing â€˜aboutâ€™ ten games surrounding the median sales output

In [110]:
median_index = (sorted_by_na_sales.shape[0] + 1) // 2

In [111]:
median_index

8299

In [131]:
sorted_by_na_sales.iloc[median_index]

Rank                     9194
Name            Dino Crisis 3
Platform                   XB
Year                     2003
Genre                  Action
Publisher              Capcom
NA_Sales                 0.08
EU_Sales                 0.03
JP_Sales                 0.03
Other_Sales                 0
Global_Sales             0.14
Name: 9192, dtype: object

In [148]:
sorted_by_na_sales.iloc[median_index - 5:  median_index + 6 ]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
10802,10804,Bladestorm: The Hundred Years' War,X360,2007.0,Action,Tecmo Koei,0.08,0.01,0.00,0.01,0.10
9569,9571,Batman: Arkham Knight,PC,2015.0,Action,Warner Bros. Interactive Entertainment,0.08,0.03,0.00,0.01,0.13
8550,8552,Wakeboarding Unleashed Featuring Shaun Murray,PS2,2003.0,Sports,Activision,0.08,0.06,0.00,0.02,0.16
10799,10801,Mind Quiz,PSP,2006.0,Action,Ubisoft,0.08,0.01,0.00,0.01,0.10
9197,9199,The Walking Dead: Season Two,XOne,2014.0,Adventure,Telltale Games,0.08,0.05,0.00,0.01,0.14
9192,9194,Dino Crisis 3,XB,2003.0,Action,Capcom,0.08,0.03,0.03,0.00,0.14
10181,10183,Smash Court Tennis 3,X360,2007.0,Sports,Atari,0.08,0.02,0.00,0.01,0.11
8802,8804,Disney's The Lion King: Simba's Mighty Adventure,PS,2000.0,Action,Activision,0.08,0.06,0.00,0.01,0.15
8724,8726,Driven,PS2,2001.0,Racing,BAM! Entertainment,0.08,0.06,0.00,0.02,0.15
10793,10795,Glory Days 2,DS,2007.0,Strategy,Ghostlight,0.08,0.00,0.00,0.01,0.10
10298,10300,National Geographic Challenge!,Wii,2011.0,Misc,Black Bean Games,0.08,0.02,0.00,0.01,0.11

In [145]:
sorted_by_top_game = video_games_df.sort_values('Global_Sales', ascending=False)

In [146]:
sorted_by_top_game[:1]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74

In [147]:
mean_sales = mean(sorted_by_top_game)

NameError: name 'mean' is not defined

In [39]:
mean_sales = mean_sales['Global_Sales']

0.5374406555006628

In [56]:
deviation_sales = np.std(sorted_by_top_game)

In [57]:
deviation_sales = deviation_sales['Global_Sales']

In [58]:
deviation_sales

1.5549810910296606

In [59]:
# (Top Game global sales - mean for global sales) / deviation_sales

In [82]:
top_game_sales = sorted_by_top_game.loc[0]['Global_Sales']

In [83]:
top_game_sales

82.74

In [86]:
result = ((top_game_sales - mean_sales) / deviation_sales)['Global_Sales']

In [87]:
result

52.864025047447576

## How does Nintendo Wii's average number of sales compare with all of the other platforms?